{'name': 'Mahaz Project Tickets',
 'version': '18.0.1.0.0',
 'author': 'Mahaz',
 'license': 'AGPL-3',
 'category': 'Services/Project',
 'depends': ['mahaz_project_task_integration', 'helpdesk_mgmt'],
 'data': ['views/project_task_views.xml', 'views/ticket_views.xml'],
 'installable': True,
 'application': False,
 'auto_install': False}
